### ISSUE TITLE
Fix PEG Sphinx Autobuild for ReadTheDocs

### ISSUE THREAD

**Issue by rbartelme** [az-digitalag/organization#274]
```Application error:
config directory doesn't contain a conf.py file (.)
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 167, in build_all_docs
    raise RuntimeError("Build failed")
RuntimeError: Build failed```

It seems the `conf.py` need to be in the configuration director for RTD

**Comment by rbartelme** [comment]
Removing a sprint milestone from this, since this is very complex and >2 pts.
